### ISSUE TITLE
How to add 2 TV's?

### ISSUE THREAD

**Issue by kevinriemens** [98oktay/homebridge-philips-tv6#16]
How can I add two Philips TV's in the house?

**Comment by ZoltXs** [comment]
Add the second television configuration to the config.json

**Comment by kevinriemens** [comment]
I see now, was just expecting an array of some kind. But i just need to add another 'PhilipsTV' accessory. Thnx.

**Comment by ZoltXs** [comment]
It works well 1 ? I can't turn on the TV, I used to work well but now I can't.

**Comment by kevinriemens** [comment]
Yes, it works well.
I have found some odd cases where it doesn't properly work (i.e. Ambilight on/off state is sometimes messed up, and volume control trough Siri is buggy at best). But the overall thing I installed this for (turning the TV on/off through Homekit) works suprisingly well.
